### ISSUE TITLE
YAML Format

### ISSUE THREAD

**Issue by tanneberger** [tud-cs/oss-collection#1]
The current YAML file includes full sentences as keys and redundant data. Shorter keys and deduplication would help to prevent cluttering the file. 

Suggestion: two yaml files
`cs-groups.yaml`
```yaml
- name: Chair of Distributed and Networked Systems
  handle: NETD
  website: https://netd.cs.tu-dresden.de
- full: Chair for Compiler Construction
  handle: CCC
  website: https://cfaed.tu-dresden.de/ccc-about
```

`oss-projects.yaml`
```yaml
- name: RIOT
  description: RIOT is the friendly Operating System for the Internet of Things.
  website: https://riot-os.org
  repository: https://github.com/RIOT-OS/RIOT
  license: LGPL
  chair: [ "NETD" ]
  founder: true
  maintainer: true
  contributor: true
  involved: true
  logo: RIOT-logo.png
```
